/**
 * Update Tailwind colors – snapshots the chromatic color scales of Tailwind CSS into `scripts/data/tailwind-colors.json`.
 *
 * Usage:
 *   node scripts/updateTailwindColors.ts
 *
 * The shade generator (`scripts/core/shades.ts`) uses these scales as its reference: every generated shade
 * follows how Tailwind's scales of the closest hues change their saturation and hue from shade `400`.
 *
 * The v3 palette is used, because it was hand-tuned within sRGB (like VS Code themes). The v4 palette is derived
 * from it, but widened for wide-gamut (P3) displays, so many of its colors can't be shown in sRGB.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { TailwindColorSnapshot } from './types.ts';
import { logError, logInfo, logSuccess } from './utils/logger.ts';

// ---------------------------------------- CONSTS ----------------------------------------

const ROOT_DIR = path.resolve(import.meta.dirname, '..');
const OUTPUT_FILE = path.join(ROOT_DIR, 'scripts', 'data', 'tailwind-colors.json');
const SOURCE_URL =
  'https://raw.githubusercontent.com/tailwindlabs/tailwindcss/v3/src/public/colors.js';

/** Tailwind's chromatic color families (the neutral gray scales are left out). */
const FAMILIES = [
  'red',
  'orange',
  'amber',
  'yellow',
  'lime',
  'green',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'fuchsia',
  'pink',
  'rose',
] as const;

const SHADE_COUNT = 11;

/** A color family object, e.g. `red: { 50: '#fef2f2', … }`. */
const FAMILY_PATTERN = /(?<family>[a-z]+): \{(?<body>[^}]*)\}/gu;
/** A shade inside a family object, e.g. `50: '#fef2f2'`. */
const SHADE_PATTERN = /(?<shade>\d+): '(?<hex>#[0-9a-f]{6})'/giu;

// ----------------------------------------- MAIN -----------------------------------------

async function main(): Promise<void> {
  try {
    logInfo(`Reading Tailwind colors from "${SOURCE_URL}"…`);
    const response = await fetch(SOURCE_URL);
    if (!response.ok) {
      throw new Error(`Request failed: ${response.status} ${response.statusText}`);
    }
    const source = await response.text();

    const families: TailwindColorSnapshot['families'] = {};
    for (const match of source.matchAll(FAMILY_PATTERN)) {
      const { family = '', body = '' } = match.groups ?? {};
      if ((FAMILIES as readonly string[]).includes(family)) {
        families[family] = Object.fromEntries(
          [...body.matchAll(SHADE_PATTERN)].map((shade) => [
            shade.groups?.shade ?? '',
            (shade.groups?.hex ?? '').toUpperCase(),
          ])
        );
      }
    }

    const incomplete = FAMILIES.filter(
      (family) => Object.keys(families[family] ?? {}).length !== SHADE_COUNT
    );
    if (incomplete.length > 0) {
      throw new Error(
        `Unrecognized palette format – incomplete families: ${incomplete.join(', ')}.`
      );
    }

    const snapshot: TailwindColorSnapshot = {
      description: 'GENERATED by `scripts/updateTailwindColors.ts` – do not edit.',
      families: Object.fromEntries(FAMILIES.map((family) => [family, families[family] ?? {}])),
      source: SOURCE_URL,
    };
    fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
    fs.writeFileSync(OUTPUT_FILE, `${JSON.stringify(snapshot, undefined, 2)}\n`);
    logSuccess(`${FAMILIES.length} color families → ${path.relative(ROOT_DIR, OUTPUT_FILE)}`);
  } catch (error) {
    logError(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}

await main();
